# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbScore',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
