# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20170811_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
