# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20170811_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='movie.Genre'),
        ),
    ]
